name: freshlens
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  camera: ^0.10.5
  video_player: ^2.5.2
  image_picker: ^1.0.7
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.12
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  permission_handler: ^11.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
   - assets/logos/
   - assets/images/
  fonts:
    - family: MPLUSRounded
      fonts:
       - asset: fonts/MPLUSRounded1c-Black.ttf
         weight: 900
       - asset: fonts/MPLUSRounded1c-ExtraBold.ttf
         weight: 800
       - asset: fonts/MPLUSRounded1c-Bold.ttf
         weight: 700
       - asset: fonts/MPLUSRounded1c-Medium.ttf
         weight: 600
       - asset: fonts/MPLUSRounded1c-Regular.ttf
         weight: 400
       - asset: fonts/MPLUSRounded1c-Light.ttf
         weight: 300
       - asset: fonts/MPLUSRounded1c-Thin.ttf
         weight: 100
    - family: Nunito
      fonts:
       - asset: fonts/Nunito-Black.ttf
         weight: 900
       - asset: fonts/Nunito-ExtraBold.ttf
         weight: 800
       - asset: fonts/Nunito-Bold.ttf
         weight: 700
       - asset: fonts/Nunito-SemiBold.ttf
         weight: 600
       - asset: fonts/Nunito-Medium.ttf
         weight: 500
       - asset: fonts/Nunito-Regular.ttf
         weight: 400
       - asset: fonts/Nunito-Light.ttf
         weight: 300
       - asset: fonts/Nunito-ExtraLight.ttf
         weight: 100
flutter_launcher_icons:
  remove_alpha_ios: true
  image_path_ios: "assets/icons/app_icon_thick.png"
  image_path_android: "assets/icons/app_icon_thick_android.png"
  #image_path: "assets/icons/app_icon_thick.png"
  #min_sdk_android: 21 # android min sdk min:16, default 21
  #adaptive_icon_background: "#FFFFFF"
  #adaptive_icon_foreground: "assets/icons/app_icon_thick.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon_thick.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/app_icon_thick.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon_thick.png"
  android:
    generate: true
    image_path: "assets/icons/app_icon_thick_android.png"